# crypto-config.yaml - 3-Org DLN-Lite Network
# Shipper: creates/sends shipments
# Carrier: moves shipments between ports
# Customs: verifies/clears shipments at the end

OrdererOrgs:
  - Name: Orderer
    Domain: dln.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Shipper
    Domain: shipper.dln.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Carrier
    Domain: carrier.dln.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Customs
    Domain: customs.dln.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
